catalogMode: prefer

shellEmulator: true
packages:
  - packages/**
  - plugins/**
  - services/**
  - examples/**
  - docs/**
  - apps/**
  - '!**/dist/**'

overrides:
  array-flatten: npm:@nolyfill/array-flatten@^1.0.44
  axios: npm:feaxios@^0.0.23
  is-core-module: npm:@nolyfill/is-core-module@^1.0.39
  isarray: npm:@nolyfill/isarray@^1.0.44
  safe-buffer: npm:@nolyfill/safe-buffer@^1.0.44
  safer-buffer: npm:@nolyfill/safer-buffer@^1.0.44
  side-channel: npm:@nolyfill/side-channel@^1.0.44
  string.prototype.matchall: npm:@nolyfill/string.prototype.matchall@^1.0.44

patchedDependencies:
  srvx@0.9.8: patches/srvx@0.9.8.patch
catalog:
  '@capacitor/cli': ^8.0.0
  '@capacitor/core': ^8.0.0
  '@capacitor/ios': ^8.0.0
  '@capacitor/local-notifications': ^8.0.0
  '@electric-sql/pglite': ^0.3.14
  '@electron-toolkit/preload': ^3.0.2
  '@guiiai/logg': ^1.2.11
  '@histoire/plugin-vue': 1.0.0-beta.1
  '@iconify-json/logos': ^1.2.10
  '@iconify-json/tabler': ^1.2.26
  '@moeru/eslint-config': 0.1.0-beta.15
  '@moeru/eventa': 1.0.0-alpha.10
  '@moeru/std': 0.1.0-beta.14
  '@nekopaw/tempora': 0.4.0-alpha.1
  '@pinia/testing': ^1.0.3
  '@proj-airi/drizzle-duckdb-wasm': ^0.4.29
  '@proj-airi/iconify-meteocons': ^0.1.4
  '@types/audioworklet': ^0.0.92
  '@types/hast': ^3.0.4
  '@types/splitpanes': ^2.2.6
  '@types/unist': ^3.0.3
  '@vueuse/core': 14.1.0
  '@xsai-ext/providers': ^0.4.0-beta.13
  '@xsai/embed': ^0.4.0-beta.13
  '@xsai/generate-speech': 0.4.0-beta.13
  '@xsai/generate-text': ^0.4.0-beta.13
  '@xsai/generate-transcription': ^0.4.0-beta.13
  '@xsai/model': ^0.4.0-beta.13
  '@xsai/shared': 0.4.0-beta.13
  '@xsai/shared-chat': 0.4.0-beta.13
  '@xsai/stream-text': ^0.4.0-beta.13
  '@xsai/tool': ^0.4.0-beta.13
  '@xsai/utils-chat': 0.4.0-beta.13
  async-mutex: 0.5.0
  better-auth: ^1.4.9
  builder-util-runtime: ^9.3.1
  drizzle-valibot: ^0.4.2
  electron: ^39.2.7
  embla-carousel-vue: ^8.6.0
  es-toolkit: 1.43.0
  histoire: 1.0.0-beta.1
  hono: 4.11.3
  idb-keyval: ^6.2.2
  injeca: ^0.1.7
  is-network-error: ^1.3.0
  nano-staged: ^0.9.0
  nanoid: 5.1.6
  ofetch: ^1.5.1
  pinia: ^3.0.4
  posthog-js: 1.306.1
  splitpanes: ^4.0.4
  std-env: ^3.10.0
  superjson: ^2.2.6
  tsx: ^4.21.0
  uncrypto: ^0.1.3
  unplugin-info: ^1.2.4
  unstorage: ^1.17.3
  valibot: 1.2.0
  vite-plugin-mkcert: ^1.17.9
  vue: ^3.5.25
  vue-sonner: 2.0.9
  xsschema: 0.4.0-beta.13
  zod: ^4.2.1

catalogs:
  rolldown-vite:
    vite: npm:rolldown-vite@^7.2.11
  vitest:
    '@vitest/browser-playwright': ^4.0.16
    '@vitest/coverage-v8': ^4.0.16
    vitest: ^4.0.16
  xsai:
    unspeech: ^0.1.11

ignoredBuiltDependencies:
  - '@prisma/client'
  - better-sqlite3

onlyBuiltDependencies:
  - '@discordjs/opus'
  - '@ffmpeg-installer/darwin-arm64'
  - '@ffmpeg-installer/linux-x64'
  - '@napi-rs/image'
  - '@parcel/watcher'
  - bufferutil
  - core-js
  - electron
  - electron-click-drag-plugin
  - electron-winstaller
  - es5-ext
  - esbuild
  - ffmpeg-static
  - less
  - msw
  - onnxruntime-node
  - protobufjs
  - sharp
  - simple-git-hooks
  - spawn-sync
  - utf-8-validate
  - vue-demi
